name: perltidy
on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:
jobs:
  perltidy:
    runs-on: ubuntu-latest
    container:
      image: perl:5.32
    steps:
      - uses: actions/checkout@v2
      - name: Fix git permissions
        # work around https://github.com/actions/checkout/issues/766
        run: git config --global --add safe.directory "$GITHUB_WORKSPACE"
      - name: perl -V
        run: perl -V
      - name: Install dependencies
        run: cpanm -n Perl::Tidy
      - name: perltidy --version
        run: perltidy --version
      - name: Run perltidy
        shell: bash
        run: |
          perltidy -b *.cgi && git diff --exit-code
